import { UserType } from '../types';
import { UserTakenCourseWithGradeType } from '../types/score-status';
export const fakeUserData: UserTakenCourseWithGradeType = {
  userTakenCourseBySemesterResponses: [
    {
      year: 2022,
      semester: '여름학기',
      averageGradeBySemester: 3.75,
      coursesAndGradeResponses: [
        {
          courseType: null,
          courseName: 'Game Theory in the Social Sciences(UC Berkeley)',
          courseCode: 'GS0700',
          credit: 3,
          grade: 'B+',
        },
        {
          courseType: null,
          courseName: 'Quantum Mechanics(UC Berkeley)',
          courseCode: 'PS3103',
          credit: 3,
          grade: 'A0',
        },
      ],
    },
    {
      year: 2022,
      semester: '2학기',
      averageGradeBySemester: 3.7,
      coursesAndGradeResponses: [
        {
          courseType: null,
          courseName: '반도체소자 (KAIST)',
          courseCode: 'EC3206',
          credit: 3,
          grade: 'B+',
        },
        {
          courseType: null,
          courseName: '물리학특강<스핀트로닉스> (KAIST)',
          courseCode: 'GS0701',
          credit: 0,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '원자력 및 양자 재료공학 개론 (KAIST)',
          courseCode: 'MA2101',
          credit: 3,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '양자역학Ⅱ(KAIST)',
          courseCode: 'PS3104',
          credit: 3,
          grade: 'B0',
        },
        {
          courseType: null,
          courseName: '통계물리학 (KAIST)',
          courseCode: 'PS3105',
          credit: 3,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '물리학실험 III (KAIST)',
          courseCode: 'PS3106',
          credit: 3,
          grade: 'A0',
        },
      ],
    },
    {
      year: 2021,
      semester: '1학기',
      averageGradeBySemester: 4.09,
      coursesAndGradeResponses: [
        {
          courseType: null,
          courseName: '공학전자기학 I',
          courseCode: 'EC2105',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '볼링',
          courseCode: 'GS0113',
          credit: 0,
          grade: 'S',
        },
        {
          courseType: null,
          courseName: '일반화학실험 Ⅰ',
          courseCode: 'GS1211',
          credit: 1,
          grade: 'B0',
        },
        {
          courseType: null,
          courseName: '미분방정식과 응용',
          courseCode: 'GS2002',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '영어 II : 이공계 글쓰기 입문',
          courseCode: 'GS2652',
          credit: 2,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '한국사회의 이해',
          courseCode: 'GS2701',
          credit: 3,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '고전역학 및 연습Ⅰ',
          courseCode: 'PS2101',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '전자기학 및 연습 Ⅰ',
          courseCode: 'PS2102',
          credit: 3,
          grade: 'B+',
        },
        {
          courseType: null,
          courseName: '현대물리 개론',
          courseCode: 'PS2201',
          credit: 3,
          grade: 'A0',
        },
      ],
    },
    {
      year: 2021,
      semester: '2학기',
      averageGradeBySemester: 3.97,
      coursesAndGradeResponses: [
        {
          courseType: null,
          courseName: '회로이론',
          courseCode: 'EC2201',
          credit: 3,
          grade: 'B+',
        },
        {
          courseType: null,
          courseName: '공학전자기학 II',
          courseCode: 'EC2205',
          credit: 3,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '컴퓨터 음악 만들기',
          courseCode: 'GS0213',
          credit: 0,
          grade: 'S',
        },
        {
          courseType: null,
          courseName: '일반생물학 실험',
          courseCode: 'GS1311',
          credit: 1,
          grade: 'B+',
        },
        {
          courseType: null,
          courseName: '행동경제학 1',
          courseCode: 'GS2732',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '전자기학 및 연습Ⅱ',
          courseCode: 'PS2103',
          credit: 3,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '수리물리 I',
          courseCode: 'PS3107',
          credit: 3,
          grade: 'B+',
        },
        {
          courseType: null,
          courseName: '일반 상대론',
          courseCode: 'PS4209',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '과학기술과 경제',
          courseCode: 'UC0901',
          credit: 1,
          grade: 'S',
        },
      ],
    },
    {
      year: 2020,
      semester: '1학기',
      averageGradeBySemester: 3.83,
      coursesAndGradeResponses: [
        {
          courseType: null,
          courseName: '축구',
          courseCode: 'GS0101',
          credit: 0,
          grade: 'S',
        },
        {
          courseType: null,
          courseName: '고급미적분학과 응용',
          courseCode: 'GS1011',
          credit: 3,
          grade: 'B0',
        },
        {
          courseType: null,
          courseName: '일반물리학 및 연습 I',
          courseCode: 'GS1101',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '일반물리학 실험 I',
          courseCode: 'GS1111',
          credit: 1,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '일반화학 및 연습 I',
          courseCode: 'GS1201',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '소프트웨어 기초와 코딩',
          courseCode: 'GS1490',
          credit: 2,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '실용적 대화법',
          courseCode: 'GS1605',
          credit: 2,
          grade: 'S',
        },
        {
          courseType: null,
          courseName: 'GIST 새내기',
          courseCode: 'GS1901',
          credit: 1,
          grade: 'S',
        },
        {
          courseType: null,
          courseName: '이산수학',
          courseCode: 'GS4010',
          credit: 3,
          grade: 'B0',
        },
      ],
    },
    {
      year: 2020,
      semester: '2학기',
      averageGradeBySemester: 4.07,
      coursesAndGradeResponses: [
        {
          courseType: null,
          courseName: '축구',
          courseCode: 'GS0101',
          credit: 0,
          grade: 'S',
        },
        {
          courseType: null,
          courseName: '일반물리학 및 연습 Ⅱ',
          courseCode: 'GS1102',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '일반물리학 실험 Ⅱ',
          courseCode: 'GS1112',
          credit: 1,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '인간 생물학',
          courseCode: 'GS1302',
          credit: 3,
          grade: 'B0',
        },
        {
          courseType: null,
          courseName: '컴퓨터 프로그래밍',
          courseCode: 'GS1401',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '글쓰기의 기초: 학술적 글쓰기',
          courseCode: 'GS1512',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '영어 Ⅰ: 신입생 영어',
          courseCode: 'GS1601',
          credit: 2,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '다변수해석학과 응용',
          courseCode: 'GS2001',
          credit: 3,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '선형대수학과 응용',
          courseCode: 'GS2004',
          credit: 3,
          grade: 'B+',
        },
      ],
    },
    {
      year: 2022,
      semester: '1학기',
      averageGradeBySemester: 3.78,
      coursesAndGradeResponses: [
        {
          courseType: null,
          courseName: '어쿠스틱기타',
          courseCode: 'GS0206',
          credit: 0,
          grade: 'S',
        },
        {
          courseType: null,
          courseName: '한국사의 이해',
          courseCode: 'GS2602',
          credit: 3,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '초기 근대의 서양',
          courseCode: 'GS2614',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: '해외경제론',
          courseCode: 'GS2730',
          credit: 3,
          grade: 'B0',
        },
        {
          courseType: null,
          courseName: '복소함수학 및 응용',
          courseCode: 'MM4002',
          credit: 3,
          grade: 'A0',
        },
        {
          courseType: null,
          courseName: '현대대수학',
          courseCode: 'MM4004',
          credit: 3,
          grade: 'B0',
        },
        {
          courseType: null,
          courseName: '전자회로',
          courseCode: 'PS3202',
          credit: 3,
          grade: 'B+',
        },
        {
          courseType: null,
          courseName: '광학개론',
          courseCode: 'PS3205',
          credit: 3,
          grade: 'A+',
        },
        {
          courseType: null,
          courseName: 'GIST대학 콜로퀴움',
          courseCode: 'UC9331',
          credit: 0,
          grade: 'S',
        },
      ],
    },
  ],
  averageGrade: 3.91,
  totalCredit: 122,
};
