# when a pull request is merged to main branch, it will be pushed to gijol-official repo automatically
on:
  pull_request:
    branches:
      - main

jobs:
  merge_to_gijol_official_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push to gijol-official repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
          branch: main
          force: true
          directory: .
          repository: gijol-official/Gijol
